// <auto-generated />
using System;
using EnergyKids.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace EnergyKids.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("EnergyKids.Models.Dispositivo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<double>("Potencia")
                    .HasColumnType("FLOAT");

                b.Property<int>("HorasPorDia")
                    .HasColumnType("NUMBER(10)");

                b.Property<int>("UsuarioId")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.HasIndex("UsuarioId");

                b.ToTable("Dispositivos");
            });

            modelBuilder.Entity("EnergyKids.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("EnergyKids.Models.DicaEconomia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)");

                b.Property<int>("UsuarioId")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.HasIndex("UsuarioId");

                b.ToTable("DicasEconomia");
            });

            modelBuilder.Entity("EnergyKids.Models.Dispositivo", b =>
            {
                b.HasOne("EnergyKids.Models.Usuario", "Usuario")
                    .WithMany("Dispositivos")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("EnergyKids.Models.DicaEconomia", b =>
            {
                b.HasOne("EnergyKids.Models.Usuario", "Usuario")
                    .WithMany()
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("EnergyKids.Models.Usuario", b =>
            {
                b.Navigation("Dispositivos");
            });
#pragma warning restore 612, 618
        }
    }
}
