trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main
      - dev

jobs:
- job: Build
  displayName: 'Build .NET Project'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: Checkout@1
    displayName: 'Checkout Source Code'

  - script: |
      dotnet build --configuration Release
    displayName: 'Build with .NET'

  - script: |
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish Project'

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Build Artifacts'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/publish
      artifactName: 'drop'

- job: Deploy
  dependsOn: Build
  displayName: 'Deploy to Azure Web App'
  pool:
    vmImage: 'windows-latest'

  variables:
    azureServiceConnection: 'conexao-energykids'
    webAppName: 'energykids'

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadPath: $(System.DefaultWorkingDirectory)

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureServiceConnection)
      appType: 'webApp'
      appName: $(webAppName)
      package: $(System.DefaultWorkingDirectory)/drop
